### ISSUE TITLE
Circular dependencies prevent webpack bundling

### ISSUE THREAD

**Issue by herrstucki** [zazuko/query-rdf-data-cube#14]
`main` and `module` point to `dist/{node|es}/datacube.js` but the built files are located at `dist/{node|es}/src/datacube.js`.

**Comment by vhf** [comment]
My mistake, fixed in `0.0.7`.

**Comment by herrstucki** [comment]
Thanks! But now something else seems broken. I get the following error:

```
TypeError: Class extends value undefined is not a constructor or null
Module.../node_modules/@zazuko/query-rdf-data-cube/dist/es/expressions/binding.js
./node_modules/@zazuko/query-rdf-data-cube/dist/es/expressions/binding.js:2
```

**Comment by vhf** [comment]
That's weird. How can I reproduce this issue?

**Comment by herrstucki** [comment]
Hmm, I can't reproduce it outside of our setup either. See https://codesandbox.io/s/epic-surf-rzl2z

However, I get the old illegal invocation of fetch error again 😅

**Comment by herrstucki** [comment]
Just guessing: Maybe webpack doesn't like this part?

https://github.com/zazuko/query-rdf-data-cube/blob/8c3692607cddf1f894536929531eb58747aaad0a/src/expressions/base.ts#L138-L139

**Comment by vhf** [comment]
Could be, yes. I don't know much about webpack and I don't have experience with frontend libraries and tooling.

**Comment by vhf** [comment]
I didn't expect this package to ever be used in a browser. Now that you seem to have a use case for it I'm trying to understand how to do this but it's much more complicated than I expected.

**Comment by herrstucki** [comment]
I found something potentially related to this: https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de (see "Fix Attempt 1" which looks similar to what you're doing). It says there that while this probably works in Node.js, it doesn't when using a bundler (example: https://codesandbox.io/s/7oxxrqwoq6).

I didn't read the whole thing to the end ;)

Also, it may have worked before because you didn't export ESM (which webpack seems to prefer)?
