### ISSUE TITLE
Export types from top-level d.ts

### ISSUE THREAD

**Issue by herrstucki** [zazuko/query-rdf-data-cube#15]
It would be great if types would be exported from the main d.ts file. Currently imports look a bit weird:

```ts
import {
  Attribute,
  Dimension,
  Measure
} from "@zazuko/query-rdf-data-cube/dist/node/components";
```

(still on v0.0.2)

**Comment by vhf** [comment]
`0.0.7` now has a `types` field in `package.json`, hopefully that should fix it: https://github.com/zazuko/query-rdf-data-cube/blob/8c3692607cddf1f894536929531eb58747aaad0a/package.json#L19

**Comment by herrstucki** [comment]
Hmm, it still doesn't work … it says

```
Module '".../node_modules/@zazuko/query-rdf-data-cube/dist/node/datacube"' has no exported member 'Attribute'.
```

etc.

**Comment by herrstucki** [comment]
I think you'd need to re-export all the classes from an `index.ts` file. Otherwise I can just import `DataCube` without specifying the path to the other files.

**Comment by vhf** [comment]
This should do it: https://github.com/zazuko/query-rdf-data-cube/blob/b69610b26c7b2b51e922901ce40888d6f563d4fb/src/index.ts

`v0.0.8`

**Comment by vhf** [comment]
I'll reopen if this is still an issue, I tested locally and it seems fine for now.
