### ISSUE TITLE
Resurgence of the fetch error

### ISSUE THREAD

**Issue by herrstucki** [zazuko/query-rdf-data-cube#18]
With the new Fetcher implementation, it seems that #6 came back from the dead 💀 😁 

Should be fixed by binding the default `fetch` to `self` or `window`.

**Comment by vhf** [comment]
Thanks, should be fixed by f6d0887f31a661718f32c890e9b95a299ee08285 in `@zazuko/query-rdf-data-cube@0.0.9`
