### ISSUE TITLE
CORS policy conflict with v0.0.9

### ISSUE THREAD

**Issue by lucguillemot** [zazuko/query-rdf-data-cube#21]
After upgrading to v0.0.9, I have this error message when querying the City of Zürich sparql endpoint:
```
Access to fetch at 'https://ld.stadt-zuerich.ch/query' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```
I think it might be due to the changes in the headers definition here. https://github.com/zazuko/query-rdf-data-cube/commit/00ab2a6f81bad900b5304710c8b54cbae38f6cc4#diff-7b6bbfa3bd9ac5a1f0158f051bf7f0fbR33

**Comment by vhf** [comment]
Thanks for the report and the fix!

[`v0.0.10`](https://github.com/zazuko/query-rdf-data-cube/blob/master/CHANGELOG.md#0010-2019-09-16)
