### ISSUE TITLE
Max 2 filters are applied

### ISSUE THREAD

**Issue by herrstucki** [zazuko/query-rdf-data-cube#28]
When more than 2 `.filter()`s are applied, only 2 actually end up in the generated SPARQL query.

My suspicion is that the `&&` operator only uses the first two args:

https://github.com/zazuko/query-rdf-data-cube/blob/fd063f178b69b876e779013d03ed0f8fcbc4fccf/src/queryutils.ts#L59-L67

**Comment by vhf** [comment]
Good catch, thanks!

**Comment by vhf** [comment]
`v0.1.2` 👍
