### ISSUE TITLE
Query is limited to 10 observations if not set

### ISSUE THREAD

**Issue by lucguillemot** [zazuko/query-rdf-data-cube#33]
As indicated [in the documentation](https://zazuko.github.io/query-rdf-data-cube/classes/query.html#limit), the number of returned observations is limited to 10 by default if `.limit()`is not set when a query is executed. Is it possible to return _all_ the observations when a limit is not defined?

**Comment by vhf** [comment]
Having a default limit prevents accidents, on some SPARQL endpoints an unfortunate query might take minutes to execute and users of the lib or endusers usually give up and retry, which puts an unnecessary load on the endpoint. For this reason we'd rather keep it.

> Is it possible to return _all_ the observations when a limit is not defined?

Not yet but I totally agree, it should be possible. What about explicitly asking for no limit, eg. `.limit(null)`?

**Comment by herrstucki** [comment]
`.limit(null)` sounds good to me!

**Comment by lucguillemot** [comment]
Thanks for your answer. Yes, I agree, `null` sounds good, and works, except for a type error ;-)

**Comment by vhf** [comment]
Published: https://www.npmjs.com/package/@zazuko/query-rdf-data-cube/v/0.2.3

**Comment by herrstucki** [comment]
Thanks @vhf !
