### ISSUE TITLE
Use arrays for multiple filters (and .select too?)

### ISSUE THREAD

**Issue by herrstucki** [zazuko/query-rdf-data-cube#35]
It would be convenient if multiple filters could be applied at once (i.e. use an array of filters). Constructing select is also a bit awkward Currently I have to do this:

```ts
let query = cube.query();

for (const f of filters) {
    query = query.filter(f);
}
```

While for `.select()`, I need an object (with a concrete Component):
```ts
for (const [key, iri] of fields) {
  query = query.select({
    [key]: [...measures, ...dimensions].find(m => m.iri.value === iri)!
  });
}

// and then:
await query.execute()
```

An improved API for the case where we have a list of fields to select and filters would be

```ts
cube.query()
  .select([["foo", dimFoo], ["bar", dimBar]]) // Similar to new Map(...)
  .filter([dimFoo.equals("baz")])
```

**Comment by vhf** [comment]
That's a great suggestion, I went with the API you suggested:

```js
cube.query()
  .select([["foo", dimFoo], ["bar", dimBar]])
  .filter([dimFoo.equals("baz")])
```

Published as `v0.3.0`.
