### ISSUE TITLE
Better types for query.execute()

### ISSUE THREAD

**Issue by herrstucki** [zazuko/query-rdf-data-cube#39]
Currently, `query.execute()` has the return type `Promise<any[]>` which should probably be something like `Promise<Record<string, NamedNode | Literal>[]>` (or use `Term` instead of  `NamedNode | Literal`?)?

The `string` key could also be made generic, so one could do `cube.query<"foo" | "bar">().execute()` => `Promise<Record<"foo" | "bar", NamedNode | Literal>>`, and the `SelectsObj` and `SelectsArr` arguments could also use that. But maybe that goes too far …

**Comment by vhf** [comment]
Good idea, thanks!

I won't be able to work on this before mid-November but I added it to my plans

**Comment by herrstucki** [comment]
Great, thanks! I could also make a PR for it (but I assume you won't merge/release that in the meantime as well).

**Comment by vhf** [comment]
PRs are welcome obviously but correct: I won't merge in the meantime :) (I'll be off for two weeks starting from this afternoon)

**Comment by herrstucki** [comment]
OK! Enjoy your vacation! 🌴

**Comment by herrstucki** [comment]
I think I got this wrong: from looking at the actual query results, a (more) correct type would be

```ts
Promise<
  Array<
    Record<
      string,
      {
        value: Literal | NamedNode;
        label?: Literal;
      }
    >
  >
>;
```

**Comment by vhf** [comment]
I checked, this looks correct indeed.
Thanks!

d2dba1c / 0.4.1
