### ISSUE TITLE
Single label on components?

### ISSUE THREAD

**Issue by herrstucki** [zazuko/query-rdf-data-cube#41]
Hi @vhf 👋 

Currently, components have an [array of labels](https://zazuko.github.io/query-rdf-data-cube/classes/component.html#labels) but as far as I can see, there's always only one, since the languages are coalesced into the most specific result in the SPARQL query anyway. 

I think it would make sense to change this to a single label, which is also the case for query result/observation values.

**Comment by vhf** [comment]
Good catch, yeah, that doesn't make sense.

**Comment by vhf** [comment]
Published as `v0.5.0`

**Comment by herrstucki** [comment]
Thanks! Just noticed that the same applies for DataCube :)

**Comment by vhf** [comment]
@herrstucki Fixed!
#44 v0.6.0
