### ISSUE TITLE
Dimensions with more than one levels

### ISSUE THREAD

**Issue by ktk** [zazuko/query-rdf-data-cube#43]
I've introduced a new dataset: Animalpest. This is used in a webapp that is currently not using this library yet and does all filtering client side.

For them to be able to switch to the library we need to introduce a way to have filtering on deeper levels. As an example:  http://yasgui.org/short/50MOflwme

`"S. Typhimurium monophasisch"@de-ch` (a phenotype) has a group it belongs to that is called  `"Serovar"@de-ch`.

So from an API perspective it should be possible to select everything that is from `Serovar` as well, which would include multiple phenotypes.

We have a lot of data where this is pretty common, most of the time those groups are linked via a `skos:broader` relation.

I think this will mostly happen for dimensions but technically it could happen for attributes as well. Measures in the case that a measure is not a literal (we don't have that in our data right now).

**Comment by ktk** [comment]
This is an example on the animalpest dataset that gets the complete data. See comments on line 29-32: http://yasgui.org/short/8BfJJA-cR

**Comment by l00mi** [comment]
Closed in favor of https://github.com/zazuko/rdf-cube-schema-viz/issues/6
