### ISSUE TITLE
Discussing the future of skos:broader support

### ISSUE THREAD

**Issue by vhf** [zazuko/query-rdf-data-cube#48]
> I haven't thought about this in detail, but it looks very useful. A few first comments:
> 
> - I assume you can use the "broader dimensions" also with `.filter()`?
> - It would be useful is to somehow "know" in advance which dimensions have "broader" entities (and on how many levels?). I.e. the result of `cube.dimensions()` should somehow reflect this. Are broader dimensions also always represented as actual dimensions of the cube?
> - There will probably be at least two kinds of "broader" relationships:
>   1. When the broader entity itself is not represented in the cube, i.e. doesn't have any observations (= is not a dimension?). E.g. when individual countries have data and continents are just used to group them conceptually.
>   2. When the broader entity actually has data. E.g. when a cube has observations for Switzerland and each individual canton, like in http://yasgui.org/short/FPHCXqCmK
> - What about dimensions that have more than one broader relationship? What would `city.broader()` return?
> - How to get the broader entity of a dimension **value** (the example you show above does this only on a dimension level)? E.g. how to go from Zürich (City) -> Zürich (Canton) -> Switzerland -> Europe …
> - How to get to narrower values? E.g. Zürich (Canton) -> all municipalities of Zürich?
> - Is there a possibility to "hop" multiple levels broader in one call? E.g. going from Zürich (City) -> Europe?
> 

_Originally posted by @herrstucki in https://github.com/zazuko/query-rdf-data-cube/pull/46#issuecomment-558979130_

**Comment by l00mi** [comment]
closed in favor of https://github.com/zazuko/rdf-cube-schema-viz/issues/6
