### ISSUE TITLE
Ability to fetch datasets of one graph only

### ISSUE THREAD

**Issue by herrstucki** [zazuko/query-rdf-data-cube#7]
Currently, i can only get all `cube.datasets()` or all `cube.graphs()` but there's no way to do `cube.datasets({graph: "http://foo.bar"})` or `cube.graphs()[0].datasets()` (not sure if the latter makes much sense).

**Comment by vhf** [comment]
@herrstucki could you please take a look at #11 and tell me if it solves this issue?

**Comment by vhf** [comment]
Implemented as:

* https://zazuko.github.io/query-rdf-data-cube/classes/_datacube_.datacube.html#datasetsbygraphiri
* and potentially https://zazuko.github.io/query-rdf-data-cube/classes/_datacube_.datacube.html#datasetbyiri
